package autogenerated

import (
	"fmt"
	"io/ioutil"
	"testing"

	"github.com/ghodss/yaml"
)

func TestYaml(t *testing.T) {
	file, err := ioutil.ReadFile("ssz_minimal_one.yaml")
	if err != nil {
		t.Fatalf("Could not load file %v", err)
	}

	s := &SszMinimalOne{}
	if err := yaml.Unmarshal(file, s); err != nil {
		t.Fatalf("Failed to Unmarshal: %v", err)
	}
	fmt.Printf("%+v", s)
}
