import * as fs from 'fs';

import {yamlToGo} from './yaml-to-go';

if (process.argv.length < 3) {
  console.error('usage: program file.yaml');
  process.exitCode = 1;
} else {
  const filepath = process.argv[2];

  console.log(`Generating go structs from ${filepath}`);
  
  const file = fs.readFileSync(filepath, 'utf8');
  const result = yamlToGo(file);
  const header = `// Code generated by yaml_to_go. DO NOT EDIT.
// source: ${filepath}

package autogenerated

`;

  fs.writeFileSync("autogenerated.yaml.go", header + result.go);
}
